version: '3.1'

services:

  # The Database

  database:
    image: mysql:5.7
    ports:
      - '3306:3306'
    
    expose:
      - '3306'

    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
    volumes:
      - ./db-erick:/var/lib/mysql
      - ./docker-config/mysql/init.sql:/docker-config/mysql/init.sql
    command: --init-file /docker-config/mysql/init.sql
  
      
     